### ISSUE TITLE
Publish new release?

### ISSUE THREAD

**Issue by qubitrenegade** [sous-chefs/trusted_certificate#19]
Hello,

Would it be possible to cut a new release to supermarket with the changes from PR #16 please?

This would make my life a whole lot easier :)

Thanks!
- QBRD

**Comment by Rudikza** [comment]
@tas50  Could you please assist with this issue?

**Comment by pvandervelde** [comment]
Any chance we're getting a new release soon? The ability to load the certs from the cookbook file store is useful.

**Comment by SlickNetAaron** [comment]
This would be great :) @tas50 @Rudikza 

Currently we have to clone the repo, which is less than optimal

I also tried loading in from a data bag, and that blew up too

**Comment by SlickNetAaron** [comment]
Cheers on the new release! Nice work, and thank you!
